# Generated by Django 5.2.11 on 2026-05-02 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadetprofile',
            name='profile_editable_until',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 12, 7, 17, 27, 225532, tzinfo=datetime.timezone.utc)),
        ),
    ]
