# Generated by Django 5.2.11 on 2026-05-03 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_cadetprofile_profile_editable_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadetprofile',
            name='profile_editable_until',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 13, 14, 40, 54, 625505, tzinfo=datetime.timezone.utc)),
        ),
    ]
